name: find_the_treasure
description: Adventure in the palm of your hands!

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
version: 1.0.0+6

environment:
  sdk: ">=2.5.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter   
  firebase_core: ^0.4.4
  firebase_auth: ^0.15.5+3
  firebase_storage: ^3.1.5
  google_sign_in: ^4.2.0
  flutter_facebook_login: ^3.0.0  
  cached_network_image: ^2.0.0
  provider: ^4.1.2
  carousel_pro: ^1.0.0  
  cloud_firestore: ^0.13.4+2
  expandable: ^4.1.2
  percent_indicator: ^2.1.1+1
  connectivity: ^0.4.8+6
  intl: ^0.16.1
  geolocator: ^5.3.0
  permission_handler: ^4.4.0+hotfix.2
  app_settings: ^3.0.1
  in_app_purchase: ^0.3.2+1
  image_picker: ^0.6.5  
  image_cropper: ^1.2.1
  device_preview: ^0.4.4
  auto_size_text: ^2.1.0
  shimmer: ^1.1.1
  package_info: ^0.4.0+17
  # plugin for launching a URL in the mobile platform.
  url_launcher: ^5.4.5
  #Share app link with friends
  share: ^0.6.4
  #When creating username - block certain words
  profanity_filter: ^1.0.2
  #New flutter animations
  animations: ^1.0.0+5
  #Confetti when user finishes a quest
  confetti: ^0.5.2
  fluttertoast: ^4.0.1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_launcher_icons:

  flutter_test:
    sdk: flutter

flutter_icons:
    image_path: 'images/4.0x/andicon.png'
    android: true
    ios: true    


# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  
  assets:    
    - images/
    - images/2.0x/
    
    - images/3.0x/
    - images/4.0x/
    - images/explore/

  

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Quicksand
      fonts:
        - asset: fonts/Quicksand-Bold.ttf
        - asset: fonts/Quicksand-Light.ttf
        - asset: fonts/Quicksand-Medium.ttf
        - asset: fonts/Quicksand-Regular.ttf
        - asset: fonts/Quicksand-SemiBold.ttf
          style: italic
    - family: JosefinSans
      fonts:
        - asset: fonts/JosefinSans-Bold.ttf
        - asset: fonts/JosefinSans-SemiBold.ttf        
              
          
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
